### ISSUE TITLE
default_allow_privilege_escalation is not a default

### ISSUE THREAD

**Issue by chrisns** [kubewarden/allow-privilege-escalation-psp-policy#9]
contrary to what the README.md says, default_allow_privilege_escalation is not defaulted, it does need to be set

```yaml
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: allowprivilegeescalation
spec:
  module: registry://ghcr.io/kubewarden/policies/allow-privilege-escalation-psp:v0.1.10
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      scope: "Namespaced"
      operations:
      - CREATE
      - UPDATE
  mutating: false
```

```
 ERROR policy_server::worker_pool: cannot spawn worker error="[registry://ghcr.io/kubewarden/policies/allow-privilege-escalation-psp:v0.1.10: settings of policy registry://ghcr.io/kubewarden/policies/allow-privilege-escalation-psp:v0.1.10 are invalid: Some(\"Error invoking settings validation callback: Error(GuestCallFailure(\\\"Guest call failed: Error decoding validation payload {}: Error(\\\\\\\"missing field `default_allow_privilege_escalation`\\\\\\\", line: 1, column: 2)\\\"))\")]"
```
